// File generated by FlutterFire CLI & configured for IdrakLisey
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_placeholder_web_key_idrak',
    appId: '1:948909504681:web:d0281b37b678120e',
    messagingSenderId: '948909504681',
    projectId: 'idraklisey-aafd7',
    authDomain: 'idraklisey-aafd7.firebaseapp.com',
    storageBucket: 'idraklisey-aafd7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_placeholder_android_key_idrak',
    appId: '1:948909504681:android:e938bf8329b3112c',
    messagingSenderId: '948909504681',
    projectId: 'idraklisey-aafd7',
    storageBucket: 'idraklisey-aafd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_placeholder_ios_key_idrak',
    appId: '1:948909504681:ios:a812398418bf7234',
    messagingSenderId: '948909504681',
    projectId: 'idraklisey-aafd7',
    storageBucket: 'idraklisey-aafd7.firebasestorage.app',
    iosBundleId: 'az.idrak.liseyi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_placeholder_macos_key_idrak',
    appId: '1:948909504681:ios:a812398418bf7234',
    messagingSenderId: '948909504681',
    projectId: 'idraklisey-aafd7',
    storageBucket: 'idraklisey-aafd7.firebasestorage.app',
    iosBundleId: 'az.idrak.liseyi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_placeholder_windows_key_idrak',
    appId: '1:948909504681:web:d0281b37b678120e',
    messagingSenderId: '948909504681',
    projectId: 'idraklisey-aafd7',
    authDomain: 'idraklisey-aafd7.firebaseapp.com',
    storageBucket: 'idraklisey-aafd7.firebasestorage.app',
  );
}
